### PR TITLE
add ip_cellForRowAtIndexPath:

### PR DESCRIPTION
**Pull request by brightredchilli**
added another helper method into CellConfiguring

### CODE REVIEW

**Comment by Benuuu** [comment]
How do all these methods work when you register two cells for the same view?

**Comment by brightredchilli** [comment]
im not sure what you mean, two cells for the same view? They would need to have different identifiers.

**Comment by Benuuu** [comment]
Ah right.  I was confused because you weren't using an identifier in your code, but the other methods call with identifier.

**Comment by Benuuu** [comment]
:shipit:

**Comment by loganwright** [comment]
:shipit:

**Comment by loganwright** [comment]
I think this is good to merge @brightredchilli

**Comment by loganwright** [comment]
closed for manual merge from 0.3.2 tag w/ @Benuuu

**Comment by brightredchilli** [comment]
thanks guys - sorry about this.

**Pull request closed without merging**
