### PR TITLE
Swift 3.2 conversion

### PR DESCRIPTION
**Pull request by tzm41**
Convert to Swift 3.2 syntax

### CODE REVIEW

**Comment by IntrepidBuildServer** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          4 Warnings
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false"><a href="https://github.com/IntrepidPursuits/swift-wisdom/blob/015a951a3d9da4c2bff79ee920ef4f12af1c0f3d/Array+UtilitiesTests.swift#L100">Array+UtilitiesTests.swift#L100</a> - <strong><a href="https://github.com/IntrepidPursuits/swift-wisdom/blob/015a951a3d9da4c2bff79ee920ef4f12af1c0f3d/SwiftWisdomTests/StandardLibrary/Array/Array+UtilitiesTests.swift#L100">SwiftWisdomTests/StandardLibrary/Array/Array+UtilitiesTests.swift#L100</a></strong>: ‘subscript(ip_safe:)’ is deprecated: Use <code>ip_safely</code> instead.  <br /><code>
        XCTAssert(testArray[ip_safe: 3] == 4)
</code></td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false"><a href="https://github.com/IntrepidPursuits/swift-wisdom/blob/015a951a3d9da4c2bff79ee920ef4f12af1c0f3d/Array+UtilitiesTests.swift#L101">Array+UtilitiesTests.swift#L101</a> - <strong><a href="https://github.com/IntrepidPursuits/swift-wisdom/blob/015a951a3d9da4c2bff79ee920ef4f12af1c0f3d/SwiftWisdomTests/StandardLibrary/Array/Array+UtilitiesTests.swift#L101">SwiftWisdomTests/StandardLibrary/Array/Array+UtilitiesTests.swift#L101</a></strong>: ‘subscript(ip_safe:)’ is deprecated: Use <code>ip_safely</code> instead.  <br /><code>
        XCTAssert(testArray[ip_safe: 8] == 9)
</code></td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false"><a href="https://github.com/IntrepidPursuits/swift-wisdom/blob/015a951a3d9da4c2bff79ee920ef4f12af1c0f3d/Array+UtilitiesTests.swift#L102">Array+UtilitiesTests.swift#L102</a> - <strong><a href="https://github.com/IntrepidPursuits/swift-wisdom/blob/015a951a3d9da4c2bff79ee920ef4f12af1c0f3d/SwiftWisdomTests/StandardLibrary/Array/Array+UtilitiesTests.swift#L102">SwiftWisdomTests/StandardLibrary/Array/Array+UtilitiesTests.swift#L102</a></strong>: ‘subscript(ip_safe:)’ is deprecated: Use <code>ip_safely</code> instead.  <br /><code>
        XCTAssertNil(testArray[ip_safe: -1])
</code></td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false"><a href="https://github.com/IntrepidPursuits/swift-wisdom/blob/015a951a3d9da4c2bff79ee920ef4f12af1c0f3d/Array+UtilitiesTests.swift#L103">Array+UtilitiesTests.swift#L103</a> - <strong><a href="https://github.com/IntrepidPursuits/swift-wisdom/blob/015a951a3d9da4c2bff79ee920ef4f12af1c0f3d/SwiftWisdomTests/StandardLibrary/Array/Array+UtilitiesTests.swift#L103">SwiftWisdomTests/StandardLibrary/Array/Array+UtilitiesTests.swift#L103</a></strong>: ‘subscript(ip_safe:)’ is deprecated: Use <code>ip_safely</code> instead.  <br /><code>
        XCTAssertNil(testArray[ip_safe: 9])
</code></td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">Executed 162 tests, with 0 failures (0 unexpected) in 0.535 (0.656) seconds</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by Benuuu** [comment]
How do these changes this affect Swift < 3.2?

I don't think we have a release strategy defined for maintaining versions, but we should probably bump at least a minor number (we're still in pre-release) and have a branch for anything that needs to be merged in for Swift < 3.2. @tzm41 do you have a sense of what we would need to do for release rollout?

**Comment by tzm41** [comment]
You could still compile it using Xcode 8 / Swift 3 settings I think, since this PR is built with Xcode 8 on Jenkins.

In terms of version bump I agree that it should be bumped for this change.

**Comment by tzm41** [comment]
With the backward compatibility I don't feel there should be much trouble for maintenance. I do think min deploy version of master should be at least 9.0 now.

**Comment by tzm41** [comment]
@Benuuu bumped spec

**Review by chow-land — APPROVED** [review]
LGTM

**Comment by tzm41** [comment]
Thanks you LGTM too @chow-land

**Pull request merged**
