### PR TITLE
Added missing double bind methods from RxExamples

### PR DESCRIPTION
**Pull request by djbrooks111**
These two methods are in https://github.com/ReactiveX/RxSwift/blob/master/RxExample/RxExample/Operators.swift, but were missing from Wisdom.

This solves an error that Xcode would throw in the following example:
```
@IBOutlet weak var textView: UITextView!
var caption = Variable("")
...
textView.rx.text <-> caption // This is where Xcode would throw a "Cannot convert type" error
```

### CODE REVIEW

**Comment by tzm41** [comment]
Use `textView.rx.text.orEmpty <-> caption`.

**Review by Benuuu — COMMENTED** [review]
Please write a basic test.

**Comment by djbrooks111** [comment]
@tzm41's suggestion worked. @Benuuu do we still want this PR then?

**Comment by Benuuu** [comment]
Lets drop it then

**Pull request closed without merging**
