### PR TITLE
Reimplement == and < operators for Version.

### LINKED ISSUE #81: Reevaluate operator overload methods
Per the conversation in PR #80 this issue is to address the reimplementation proposals made for some of the operator overload methods within `Version.swift`

### PR DESCRIPTION
**Pull request by Tom-Le**
Based on suggestions in #80. Resolves #81.

### CODE REVIEW

**Comment by vinnyt** [comment]
tests?

**Comment by Tom-Le** [comment]
There's already a `VersionTests` for this struct. I ran it before opening this PR with no issue.

**Comment by ButkiewiczP** [comment]
jenkins tests will fail until #82 is merged

**Review by paulrolfe — APPROVED** [review]
rebase please. 👍

**Pull request merged**
