### PR TITLE
gradient crash fix

### PR DESCRIPTION
**Pull request by paulrolfe**

### CODE REVIEW

**Comment by Benuuu** [comment]
:shipit:

**Comment by loganwright** [comment]
:shipit: (bump podspec, tag etc.)

**Comment by Benuuu** [comment]
@LoganWright the bump podspec etc be independent of the PR right?

**Comment by loganwright** [comment]
@Benuuu We have been bumping/tagging it on the PR, then merging it in together. Any arguments against that pattern?

**Pull request merged**
