### PR TITLE
Lw/rx

### PR DESCRIPTION
**Pull request by loganwright**
@Benuuu @vinnyt 

I got these from your project, if there's any more that could be added, that'd be awesome!

### CODE REVIEW

**Comment by vinnyt** [comment]
:+1: :+1:

**Comment by Benuuu** [comment]
:shipit: 

Not sure if we need / want examples somewhere.

**Comment by vinnyt** [comment]
We should consider cooking up some examples

**Comment by loganwright** [comment]
@Benuuu @vinnyt I don't feel qualified to write examples yet, if one of you guys wouldn't mind adding some, that would be :rocket:!

**Comment by vinnyt** [comment]
I can take a cut at this in a couple of weeks  unless @Benuuu can get to it sooner.

**Pull request merged**
