### PR TITLE
Alex/swiftlint violation fixes

### PR DESCRIPTION
**Pull request by alexpersian**
Addresses the violations outstanding after initial SwiftLint integration.

* The vast majority (~140) of violations were from our common naming scheme of `ip_methodName`, and the only other naming violations were from uppercase method names such as `After`, `Repeat`, etc. For this reason I've disabled the `identifier_name` rule from this our lint file for this project. 

* The violations left were from `force_cast` and `force_try` in two files. In these instances the failure path is not defined, and we _do not_ want the program to continue if these checks would fail. For that reason I've selectively disabled the rules around these blocks. 

After this PR violations are at `15 minor, 0 serious in 55 files`.

### CODE REVIEW

**Comment by IntrepidBuildServer** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          4 Warnings
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false"><a href="https://github.com/IntrepidPursuits/swift-wisdom/blob/6d82bcc7ac4cdbde45b60c811ca532313a34dd44/Array+UtilitiesTests.swift#L100">Array+UtilitiesTests.swift#L100</a> - <strong><a href="https://github.com/IntrepidPursuits/swift-wisdom/blob/6d82bcc7ac4cdbde45b60c811ca532313a34dd44/SwiftWisdomTests/StandardLibrary/Array/Array+UtilitiesTests.swift#L100">SwiftWisdomTests/StandardLibrary/Array/Array+UtilitiesTests.swift#L100</a></strong>: ‘subscript(ip_safe:)’ is deprecated: Use <code>ip_safely</code> instead.  <br /><code>
        XCTAssert(testArray[ip_safe: 3] == 4)
</code></td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false"><a href="https://github.com/IntrepidPursuits/swift-wisdom/blob/6d82bcc7ac4cdbde45b60c811ca532313a34dd44/Array+UtilitiesTests.swift#L101">Array+UtilitiesTests.swift#L101</a> - <strong><a href="https://github.com/IntrepidPursuits/swift-wisdom/blob/6d82bcc7ac4cdbde45b60c811ca532313a34dd44/SwiftWisdomTests/StandardLibrary/Array/Array+UtilitiesTests.swift#L101">SwiftWisdomTests/StandardLibrary/Array/Array+UtilitiesTests.swift#L101</a></strong>: ‘subscript(ip_safe:)’ is deprecated: Use <code>ip_safely</code> instead.  <br /><code>
        XCTAssert(testArray[ip_safe: 8] == 9)
</code></td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false"><a href="https://github.com/IntrepidPursuits/swift-wisdom/blob/6d82bcc7ac4cdbde45b60c811ca532313a34dd44/Array+UtilitiesTests.swift#L102">Array+UtilitiesTests.swift#L102</a> - <strong><a href="https://github.com/IntrepidPursuits/swift-wisdom/blob/6d82bcc7ac4cdbde45b60c811ca532313a34dd44/SwiftWisdomTests/StandardLibrary/Array/Array+UtilitiesTests.swift#L102">SwiftWisdomTests/StandardLibrary/Array/Array+UtilitiesTests.swift#L102</a></strong>: ‘subscript(ip_safe:)’ is deprecated: Use <code>ip_safely</code> instead.  <br /><code>
        XCTAssertNil(testArray[ip_safe: -1])
</code></td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false"><a href="https://github.com/IntrepidPursuits/swift-wisdom/blob/6d82bcc7ac4cdbde45b60c811ca532313a34dd44/Array+UtilitiesTests.swift#L103">Array+UtilitiesTests.swift#L103</a> - <strong><a href="https://github.com/IntrepidPursuits/swift-wisdom/blob/6d82bcc7ac4cdbde45b60c811ca532313a34dd44/SwiftWisdomTests/StandardLibrary/Array/Array+UtilitiesTests.swift#L103">SwiftWisdomTests/StandardLibrary/Array/Array+UtilitiesTests.swift#L103</a></strong>: ‘subscript(ip_safe:)’ is deprecated: Use <code>ip_safely</code> instead.  <br /><code>
        XCTAssertNil(testArray[ip_safe: 9])
</code></td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">Executed 142 tests, with 0 failures (0 unexpected) in 0.194 (0.250) seconds</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Review by mayasaxena — COMMENTED** [review]
If we want to leave `identifier_name` in, it's possible to include `_` in the rule's configuration under `allowed_symbols`

**Comment by alexpersian** [comment]
@mayasaxena that's a solid option. I'll look into that

**Comment by tzm41** [comment]
This means every project using those items will need to ignore this rule to avoid getting violations. Should we rethink the naming convention here, or rethink the naming convention rule in SwiftLint for all projects?

**Comment by alexpersian** [comment]
@tzm41 this rule would only apply to the definition (so here in swift-wisdom), not in other projects that are using these methods.

**Comment by IntrepidBuildServer** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          4 Warnings
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false"><a href="https://github.com/IntrepidPursuits/swift-wisdom/blob/c822f347fa9c755f0349165d7c443d0c8aaa73a9/Array+UtilitiesTests.swift#L100">Array+UtilitiesTests.swift#L100</a> - <strong><a href="https://github.com/IntrepidPursuits/swift-wisdom/blob/c822f347fa9c755f0349165d7c443d0c8aaa73a9/SwiftWisdomTests/StandardLibrary/Array/Array+UtilitiesTests.swift#L100">SwiftWisdomTests/StandardLibrary/Array/Array+UtilitiesTests.swift#L100</a></strong>: ‘subscript(ip_safe:)’ is deprecated: Use <code>ip_safely</code> instead.  <br /><code>
        XCTAssert(testArray[ip_safe: 3] == 4)
</code></td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false"><a href="https://github.com/IntrepidPursuits/swift-wisdom/blob/c822f347fa9c755f0349165d7c443d0c8aaa73a9/Array+UtilitiesTests.swift#L101">Array+UtilitiesTests.swift#L101</a> - <strong><a href="https://github.com/IntrepidPursuits/swift-wisdom/blob/c822f347fa9c755f0349165d7c443d0c8aaa73a9/SwiftWisdomTests/StandardLibrary/Array/Array+UtilitiesTests.swift#L101">SwiftWisdomTests/StandardLibrary/Array/Array+UtilitiesTests.swift#L101</a></strong>: ‘subscript(ip_safe:)’ is deprecated: Use <code>ip_safely</code> instead.  <br /><code>
        XCTAssert(testArray[ip_safe: 8] == 9)
</code></td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false"><a href="https://github.com/IntrepidPursuits/swift-wisdom/blob/c822f347fa9c755f0349165d7c443d0c8aaa73a9/Array+UtilitiesTests.swift#L102">Array+UtilitiesTests.swift#L102</a> - <strong><a href="https://github.com/IntrepidPursuits/swift-wisdom/blob/c822f347fa9c755f0349165d7c443d0c8aaa73a9/SwiftWisdomTests/StandardLibrary/Array/Array+UtilitiesTests.swift#L102">SwiftWisdomTests/StandardLibrary/Array/Array+UtilitiesTests.swift#L102</a></strong>: ‘subscript(ip_safe:)’ is deprecated: Use <code>ip_safely</code> instead.  <br /><code>
        XCTAssertNil(testArray[ip_safe: -1])
</code></td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false"><a href="https://github.com/IntrepidPursuits/swift-wisdom/blob/c822f347fa9c755f0349165d7c443d0c8aaa73a9/Array+UtilitiesTests.swift#L103">Array+UtilitiesTests.swift#L103</a> - <strong><a href="https://github.com/IntrepidPursuits/swift-wisdom/blob/c822f347fa9c755f0349165d7c443d0c8aaa73a9/SwiftWisdomTests/StandardLibrary/Array/Array+UtilitiesTests.swift#L103">SwiftWisdomTests/StandardLibrary/Array/Array+UtilitiesTests.swift#L103</a></strong>: ‘subscript(ip_safe:)’ is deprecated: Use <code>ip_safely</code> instead.  <br /><code>
        XCTAssertNil(testArray[ip_safe: 9])
</code></td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">Executed 142 tests, with 0 failures (0 unexpected) in 0.520 (0.653) seconds</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Review by MaxHasADHD — APPROVED** [review]

**Review by bobgilmore — APPROVED** [review]

**Comment by ghost** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          4 Warnings
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false"><a href="https://github.com/IntrepidPursuits/swift-wisdom/blob/1fd6300e36874bef7af8367040b2e713c609521a/Array+UtilitiesTests.swift#L100">Array+UtilitiesTests.swift#L100</a> - <strong><a href="https://github.com/IntrepidPursuits/swift-wisdom/blob/1fd6300e36874bef7af8367040b2e713c609521a/SwiftWisdomTests/StandardLibrary/Array/Array+UtilitiesTests.swift#L100">SwiftWisdomTests/StandardLibrary/Array/Array+UtilitiesTests.swift#L100</a></strong>: ‘subscript(ip_safe:)’ is deprecated: Use <code>ip_safely</code> instead.  <br /><code>
        XCTAssert(testArray[ip_safe: 3] == 4)
</code></td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false"><a href="https://github.com/IntrepidPursuits/swift-wisdom/blob/1fd6300e36874bef7af8367040b2e713c609521a/Array+UtilitiesTests.swift#L101">Array+UtilitiesTests.swift#L101</a> - <strong><a href="https://github.com/IntrepidPursuits/swift-wisdom/blob/1fd6300e36874bef7af8367040b2e713c609521a/SwiftWisdomTests/StandardLibrary/Array/Array+UtilitiesTests.swift#L101">SwiftWisdomTests/StandardLibrary/Array/Array+UtilitiesTests.swift#L101</a></strong>: ‘subscript(ip_safe:)’ is deprecated: Use <code>ip_safely</code> instead.  <br /><code>
        XCTAssert(testArray[ip_safe: 8] == 9)
</code></td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false"><a href="https://github.com/IntrepidPursuits/swift-wisdom/blob/1fd6300e36874bef7af8367040b2e713c609521a/Array+UtilitiesTests.swift#L102">Array+UtilitiesTests.swift#L102</a> - <strong><a href="https://github.com/IntrepidPursuits/swift-wisdom/blob/1fd6300e36874bef7af8367040b2e713c609521a/SwiftWisdomTests/StandardLibrary/Array/Array+UtilitiesTests.swift#L102">SwiftWisdomTests/StandardLibrary/Array/Array+UtilitiesTests.swift#L102</a></strong>: ‘subscript(ip_safe:)’ is deprecated: Use <code>ip_safely</code> instead.  <br /><code>
        XCTAssertNil(testArray[ip_safe: -1])
</code></td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false"><a href="https://github.com/IntrepidPursuits/swift-wisdom/blob/1fd6300e36874bef7af8367040b2e713c609521a/Array+UtilitiesTests.swift#L103">Array+UtilitiesTests.swift#L103</a> - <strong><a href="https://github.com/IntrepidPursuits/swift-wisdom/blob/1fd6300e36874bef7af8367040b2e713c609521a/SwiftWisdomTests/StandardLibrary/Array/Array+UtilitiesTests.swift#L103">SwiftWisdomTests/StandardLibrary/Array/Array+UtilitiesTests.swift#L103</a></strong>: ‘subscript(ip_safe:)’ is deprecated: Use <code>ip_safely</code> instead.  <br /><code>
        XCTAssertNil(testArray[ip_safe: 9])
</code></td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">Executed 142 tests, with 0 failures (0 unexpected) in 0.190 (0.246) seconds</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Pull request merged**
